# Generated by Django 3.0.6 on 2020-05-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='busquedas', verbose_name='Imagen')),
                ('datos', models.TextField(blank=True, null=True, verbose_name='Datos')),
            ],
        ),
    ]
